name: Update gist with Todoist items
on:
  push:
  schedule:
    - cron: '0 * * * *' # At minute 0 (AKA every hour)
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install NPM dependencies
        run: npm ci
      - name: Update gist
        run: npm start
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          TODOIST_API_ENDPOINT: ${{ secrets.TODOIST_API_ENDPOINT }}

